/**
 * google.golang.org/genproto/googleapis/longrunning/operations.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LongrunningOperation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./LongrunningOperation'));
  } else {
    // Browser globals (root is window)
    if (!root.Googlegolangorggenprotogoogleapislongrunningoperationsproto) {
      root.Googlegolangorggenprotogoogleapislongrunningoperationsproto = {};
    }
    root.Googlegolangorggenprotogoogleapislongrunningoperationsproto.LongrunningListOperationsResponse = factory(root.Googlegolangorggenprotogoogleapislongrunningoperationsproto.ApiClient, root.Googlegolangorggenprotogoogleapislongrunningoperationsproto.LongrunningOperation);
  }
}(this, function(ApiClient, LongrunningOperation) {
  'use strict';




  /**
   * The LongrunningListOperationsResponse model module.
   * @module model/LongrunningListOperationsResponse
   * @version 1
   */

  /**
   * Constructs a new <code>LongrunningListOperationsResponse</code>.
   * The response message for [Operations.ListOperations][google.longrunning.Operations.ListOperations].
   * @alias module:model/LongrunningListOperationsResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>LongrunningListOperationsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LongrunningListOperationsResponse} obj Optional instance to populate.
   * @return {module:model/LongrunningListOperationsResponse} The populated <code>LongrunningListOperationsResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('operations')) {
        obj['operations'] = ApiClient.convertToType(data['operations'], [LongrunningOperation]);
      }
      if (data.hasOwnProperty('next_page_token')) {
        obj['next_page_token'] = ApiClient.convertToType(data['next_page_token'], 'String');
      }
    }
    return obj;
  }

  /**
   * A list of operations that matches the specified filter in the request.
   * @member {Array.<module:model/LongrunningOperation>} operations
   */
  exports.prototype['operations'] = undefined;
  /**
   * The standard List next-page token.
   * @member {String} next_page_token
   */
  exports.prototype['next_page_token'] = undefined;



  return exports;
}));


