/**
 * uweb/v1/uweb.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProtobufEmpty', 'model/V1CreateTaskRequest', 'model/V1GetCaptchaResponse', 'model/V1GetNodesResponse', 'model/V1ListLinksResponse', 'model/V1ListNodesResponse', 'model/V1LoginRequest', 'model/V1LoginResponse', 'model/V1Node', 'model/V1SSHLink', 'model/V1UpdateTask', 'api/MsshApi', 'api/RootApi', 'api/UpdaterApi', 'api/UsersApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ProtobufEmpty'), require('./model/V1CreateTaskRequest'), require('./model/V1GetCaptchaResponse'), require('./model/V1GetNodesResponse'), require('./model/V1ListLinksResponse'), require('./model/V1ListNodesResponse'), require('./model/V1LoginRequest'), require('./model/V1LoginResponse'), require('./model/V1Node'), require('./model/V1SSHLink'), require('./model/V1UpdateTask'), require('./api/MsshApi'), require('./api/RootApi'), require('./api/UpdaterApi'), require('./api/UsersApi'));
  }
}(function(ApiClient, ProtobufEmpty, V1CreateTaskRequest, V1GetCaptchaResponse, V1GetNodesResponse, V1ListLinksResponse, V1ListNodesResponse, V1LoginRequest, V1LoginResponse, V1Node, V1SSHLink, V1UpdateTask, MsshApi, RootApi, UpdaterApi, UsersApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Uwebv1uwebproto = require('index'); // See note below*.
   * var xxxSvc = new Uwebv1uwebproto.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Uwebv1uwebproto.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Uwebv1uwebproto.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Uwebv1uwebproto.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ProtobufEmpty model constructor.
     * @property {module:model/ProtobufEmpty}
     */
    ProtobufEmpty: ProtobufEmpty,
    /**
     * The V1CreateTaskRequest model constructor.
     * @property {module:model/V1CreateTaskRequest}
     */
    V1CreateTaskRequest: V1CreateTaskRequest,
    /**
     * The V1GetCaptchaResponse model constructor.
     * @property {module:model/V1GetCaptchaResponse}
     */
    V1GetCaptchaResponse: V1GetCaptchaResponse,
    /**
     * The V1GetNodesResponse model constructor.
     * @property {module:model/V1GetNodesResponse}
     */
    V1GetNodesResponse: V1GetNodesResponse,
    /**
     * The V1ListLinksResponse model constructor.
     * @property {module:model/V1ListLinksResponse}
     */
    V1ListLinksResponse: V1ListLinksResponse,
    /**
     * The V1ListNodesResponse model constructor.
     * @property {module:model/V1ListNodesResponse}
     */
    V1ListNodesResponse: V1ListNodesResponse,
    /**
     * The V1LoginRequest model constructor.
     * @property {module:model/V1LoginRequest}
     */
    V1LoginRequest: V1LoginRequest,
    /**
     * The V1LoginResponse model constructor.
     * @property {module:model/V1LoginResponse}
     */
    V1LoginResponse: V1LoginResponse,
    /**
     * The V1Node model constructor.
     * @property {module:model/V1Node}
     */
    V1Node: V1Node,
    /**
     * The V1SSHLink model constructor.
     * @property {module:model/V1SSHLink}
     */
    V1SSHLink: V1SSHLink,
    /**
     * The V1UpdateTask model constructor.
     * @property {module:model/V1UpdateTask}
     */
    V1UpdateTask: V1UpdateTask,
    /**
     * The MsshApi service constructor.
     * @property {module:api/MsshApi}
     */
    MsshApi: MsshApi,
    /**
     * The RootApi service constructor.
     * @property {module:api/RootApi}
     */
    RootApi: RootApi,
    /**
     * The UpdaterApi service constructor.
     * @property {module:api/UpdaterApi}
     */
    UpdaterApi: UpdaterApi,
    /**
     * The UsersApi service constructor.
     * @property {module:api/UsersApi}
     */
    UsersApi: UsersApi
  };

  return exports;
}));
