/**
 * google.golang.org/genproto/googleapis/longrunning/operations.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Googlegolangorggenprotogoogleapislongrunningoperationsproto);
  }
}(this, function(expect, Googlegolangorggenprotogoogleapislongrunningoperationsproto) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Googlegolangorggenprotogoogleapislongrunningoperationsproto.OperationsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OperationsApi', function() {
    describe('cancelOperation', function() {
      it('should call cancelOperation successfully', function(done) {
        //uncomment below and update the code to test cancelOperation
        //instance.cancelOperation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteOperation', function() {
      it('should call deleteOperation successfully', function(done) {
        //uncomment below and update the code to test deleteOperation
        //instance.deleteOperation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOperation', function() {
      it('should call getOperation successfully', function(done) {
        //uncomment below and update the code to test getOperation
        //instance.getOperation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
