/**
 * uweb/v1/uweb.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/V1SSHLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./V1SSHLink'));
  } else {
    // Browser globals (root is window)
    if (!root.Uwebv1uwebproto) {
      root.Uwebv1uwebproto = {};
    }
    root.Uwebv1uwebproto.V1CreateTaskRequest = factory(root.Uwebv1uwebproto.ApiClient, root.Uwebv1uwebproto.V1SSHLink);
  }
}(this, function(ApiClient, V1SSHLink) {
  'use strict';




  /**
   * The V1CreateTaskRequest model module.
   * @module model/V1CreateTaskRequest
   * @version 1
   */

  /**
   * Constructs a new <code>V1CreateTaskRequest</code>.
   * @alias module:model/V1CreateTaskRequest
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>V1CreateTaskRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1CreateTaskRequest} obj Optional instance to populate.
   * @return {module:model/V1CreateTaskRequest} The populated <code>V1CreateTaskRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('patch_path')) {
        obj['patch_path'] = ApiClient.convertToType(data['patch_path'], 'String');
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [V1SSHLink]);
      }
    }
    return obj;
  }

  /**
   * @member {String} patch_path
   */
  exports.prototype['patch_path'] = undefined;
  /**
   * @member {Array.<module:model/V1SSHLink>} links
   */
  exports.prototype['links'] = undefined;



  return exports;
}));


