/**
 * uweb/v1/uweb.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/V1Node'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./V1Node'));
  } else {
    // Browser globals (root is window)
    if (!root.Uwebv1uwebproto) {
      root.Uwebv1uwebproto = {};
    }
    root.Uwebv1uwebproto.V1ListNodesResponse = factory(root.Uwebv1uwebproto.ApiClient, root.Uwebv1uwebproto.V1Node);
  }
}(this, function(ApiClient, V1Node) {
  'use strict';




  /**
   * The V1ListNodesResponse model module.
   * @module model/V1ListNodesResponse
   * @version 1
   */

  /**
   * Constructs a new <code>V1ListNodesResponse</code>.
   * @alias module:model/V1ListNodesResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>V1ListNodesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1ListNodesResponse} obj Optional instance to populate.
   * @return {module:model/V1ListNodesResponse} The populated <code>V1ListNodesResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('nodes')) {
        obj['nodes'] = ApiClient.convertToType(data['nodes'], [V1Node]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/V1Node>} nodes
   */
  exports.prototype['nodes'] = undefined;



  return exports;
}));


