/**
 * uweb/v1/uweb.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Uwebv1uwebproto) {
      root.Uwebv1uwebproto = {};
    }
    root.Uwebv1uwebproto.V1SSHLink = factory(root.Uwebv1uwebproto.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The V1SSHLink model module.
   * @module model/V1SSHLink
   * @version 1
   */

  /**
   * Constructs a new <code>V1SSHLink</code>.
   * @alias module:model/V1SSHLink
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>V1SSHLink</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1SSHLink} obj Optional instance to populate.
   * @return {module:model/V1SSHLink} The populated <code>V1SSHLink</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('addr')) {
        obj['addr'] = ApiClient.convertToType(data['addr'], 'String');
      }
      if (data.hasOwnProperty('user')) {
        obj['user'] = ApiClient.convertToType(data['user'], 'String');
      }
      if (data.hasOwnProperty('pass')) {
        obj['pass'] = ApiClient.convertToType(data['pass'], 'String');
      }
      if (data.hasOwnProperty('sid')) {
        obj['sid'] = ApiClient.convertToType(data['sid'], 'String');
      }
      if (data.hasOwnProperty('guid')) {
        obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} addr
   */
  exports.prototype['addr'] = undefined;
  /**
   * @member {String} user
   */
  exports.prototype['user'] = undefined;
  /**
   * @member {String} pass
   */
  exports.prototype['pass'] = undefined;
  /**
   * @member {String} sid
   */
  exports.prototype['sid'] = undefined;
  /**
   * @member {String} guid
   */
  exports.prototype['guid'] = undefined;



  return exports;
}));


