/**
 * uweb/v1/uweb.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProtobufEmpty', 'model/V1ListLinksResponse', 'model/V1SSHLink'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ProtobufEmpty'), require('../model/V1ListLinksResponse'), require('../model/V1SSHLink'));
  } else {
    // Browser globals (root is window)
    if (!root.Uwebv1uwebproto) {
      root.Uwebv1uwebproto = {};
    }
    root.Uwebv1uwebproto.MsshApi = factory(root.Uwebv1uwebproto.ApiClient, root.Uwebv1uwebproto.ProtobufEmpty, root.Uwebv1uwebproto.V1ListLinksResponse, root.Uwebv1uwebproto.V1SSHLink);
  }
}(this, function(ApiClient, ProtobufEmpty, V1ListLinksResponse, V1SSHLink) {
  'use strict';

  /**
   * Mssh service.
   * @module api/MsshApi
   * @version 1
   */

  /**
   * Constructs a new MsshApi. 
   * @alias module:api/MsshApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createLink operation.
     * @callback module:api/MsshApi~createLinkCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1SSHLink} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/V1SSHLink} body 
     * @param {module:api/MsshApi~createLinkCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1SSHLink}
     */
    this.createLink = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createLink");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = V1SSHLink;

      return this.apiClient.callApi(
        '/uweb/v1/mssh/links', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteLink operation.
     * @callback module:api/MsshApi~deleteLinkCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ProtobufEmpty} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} guid 
     * @param {module:api/MsshApi~deleteLinkCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ProtobufEmpty}
     */
    this.deleteLink = function(guid, callback) {
      var postBody = null;

      // verify the required parameter 'guid' is set
      if (guid === undefined || guid === null) {
        throw new Error("Missing the required parameter 'guid' when calling deleteLink");
      }


      var pathParams = {
        'guid': guid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ProtobufEmpty;

      return this.apiClient.callApi(
        '/uweb/v1/mssh/links/{guid}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getLink operation.
     * @callback module:api/MsshApi~getLinkCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1SSHLink} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 树结构
     * @param {String} guid 
     * @param {module:api/MsshApi~getLinkCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1SSHLink}
     */
    this.getLink = function(guid, callback) {
      var postBody = null;

      // verify the required parameter 'guid' is set
      if (guid === undefined || guid === null) {
        throw new Error("Missing the required parameter 'guid' when calling getLink");
      }


      var pathParams = {
        'guid': guid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = V1SSHLink;

      return this.apiClient.callApi(
        '/uweb/v1/mssh/links/{guid}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the listLinks operation.
     * @callback module:api/MsshApi~listLinksCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ListLinksResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 平铺列表
     * @param {module:api/MsshApi~listLinksCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ListLinksResponse}
     */
    this.listLinks = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = V1ListLinksResponse;

      return this.apiClient.callApi(
        '/uweb/v1/mssh/links:list', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateLink operation.
     * @callback module:api/MsshApi~updateLinkCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1SSHLink} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} linkGuid 
     * @param {module:model/V1SSHLink} body 
     * @param {module:api/MsshApi~updateLinkCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1SSHLink}
     */
    this.updateLink = function(linkGuid, body, callback) {
      var postBody = body;

      // verify the required parameter 'linkGuid' is set
      if (linkGuid === undefined || linkGuid === null) {
        throw new Error("Missing the required parameter 'linkGuid' when calling updateLink");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateLink");
      }


      var pathParams = {
        'link.guid': linkGuid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = V1SSHLink;

      return this.apiClient.callApi(
        '/uweb/v1/mssh/links/{link.guid}', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
