/**
 * uweb/v1/uweb.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/V1CreateTaskRequest', 'model/V1UpdateTask'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/V1CreateTaskRequest'), require('../model/V1UpdateTask'));
  } else {
    // Browser globals (root is window)
    if (!root.Uwebv1uwebproto) {
      root.Uwebv1uwebproto = {};
    }
    root.Uwebv1uwebproto.UpdaterApi = factory(root.Uwebv1uwebproto.ApiClient, root.Uwebv1uwebproto.V1CreateTaskRequest, root.Uwebv1uwebproto.V1UpdateTask);
  }
}(this, function(ApiClient, V1CreateTaskRequest, V1UpdateTask) {
  'use strict';

  /**
   * Updater service.
   * @module api/UpdaterApi
   * @version 1
   */

  /**
   * Constructs a new UpdaterApi. 
   * @alias module:api/UpdaterApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createTask operation.
     * @callback module:api/UpdaterApi~createTaskCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1UpdateTask} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 树结构
     * @param {module:model/V1CreateTaskRequest} body 
     * @param {module:api/UpdaterApi~createTaskCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1UpdateTask}
     */
    this.createTask = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createTask");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = V1UpdateTask;

      return this.apiClient.callApi(
        '/uweb/v1/updater/tasks', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getTask operation.
     * @callback module:api/UpdaterApi~getTaskCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1UpdateTask} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 平铺列表
     * @param {String} id 
     * @param {module:api/UpdaterApi~getTaskCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1UpdateTask}
     */
    this.getTask = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getTask");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = V1UpdateTask;

      return this.apiClient.callApi(
        '/uweb/v1/updater/tasks/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
