/**
 * uweb/v1/uweb.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/V1GetCaptchaResponse', 'model/V1LoginRequest', 'model/V1LoginResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/V1GetCaptchaResponse'), require('../model/V1LoginRequest'), require('../model/V1LoginResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Uwebv1uwebproto) {
      root.Uwebv1uwebproto = {};
    }
    root.Uwebv1uwebproto.UsersApi = factory(root.Uwebv1uwebproto.ApiClient, root.Uwebv1uwebproto.V1GetCaptchaResponse, root.Uwebv1uwebproto.V1LoginRequest, root.Uwebv1uwebproto.V1LoginResponse);
  }
}(this, function(ApiClient, V1GetCaptchaResponse, V1LoginRequest, V1LoginResponse) {
  'use strict';

  /**
   * Users service.
   * @module api/UsersApi
   * @version 1
   */

  /**
   * Constructs a new UsersApi. 
   * @alias module:api/UsersApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getCaptcha operation.
     * @callback module:api/UsersApi~getCaptchaCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1GetCaptchaResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 平铺列表
     * @param {module:api/UsersApi~getCaptchaCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1GetCaptchaResponse}
     */
    this.getCaptcha = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = V1GetCaptchaResponse;

      return this.apiClient.callApi(
        '/uweb/v1/users:captcha', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the login operation.
     * @callback module:api/UsersApi~loginCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1LoginResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 树结构
     * @param {module:model/V1LoginRequest} body 
     * @param {module:api/UsersApi~loginCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1LoginResponse}
     */
    this.login = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling login");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = V1LoginResponse;

      return this.apiClient.callApi(
        '/uweb/v1/users:login', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
